export const INIT_PERMISSIONS = [
  {
    name: 'Get Subscriber with paginate',
    apiPath: '/api/v1/subscribers',
    method: 'GET',
    module: 'SUBSCRIBERS',
  },
  {
    name: 'Create Subscriber',
    apiPath: '/api/v1/subscribers',
    method: 'POST',
    module: 'SUBSCRIBERS',
  },
  {
    name: 'Update Subscriber',
    apiPath: '/api/v1/subscribers/:id',
    method: 'PATCH',
    module: 'SUBSCRIBERS',
  },
  {
    name: 'Delete Subscriber',
    apiPath: '/api/v1/subscribers/:id',
    method: 'DELETE',
    module: 'SUBSCRIBERS',
  },
  {
    name: 'Get Subscriber by id',
    apiPath: '/api/v1/subscribers/:id',
    method: 'GET',
    module: 'SUBSCRIBERS',
  },
  {
    name: 'Get Account',
    apiPath: '/api/v1/auth/account',
    method: 'GET',
    module: 'AUTH',
  },
  {
    name: 'Logout',
    apiPath: '/api/v1/auth/logout',
    method: 'POST',
    module: 'AUTH',
  },
  {
    name: 'Get Company with paginate',
    apiPath: '/api/v1/companies',
    method: 'GET',
    module: 'COMPANIES',
  },
  {
    name: 'Create Company',
    apiPath: '/api/v1/companies',
    method: 'POST',
    module: 'COMPANIES',
  },
  {
    name: 'Update Company',
    apiPath: '/api/v1/companies/:id',
    method: 'PATCH',
    module: 'COMPANIES',
  },
  {
    name: 'Delete Company',
    apiPath: '/api/v1/companies/:id',
    method: 'DELETE',
    module: 'COMPANIES',
  },
  {
    name: 'Get Company by id',
    apiPath: '/api/v1/companies/:id',
    method: 'GET',
    module: 'COMPANIES',
  },
  {
    name: 'Create User',
    apiPath: '/api/v1/users',
    method: 'POST',
    module: 'USERS',
  },
  {
    name: 'Get User by Id',
    apiPath: '/api/v1/users/:id',
    method: 'GET',
    module: 'USERS',
  },
  {
    name: 'Get User with paginate',
    apiPath: '/api/v1/users',
    method: 'GET',
    module: 'USERS',
  },
  {
    name: 'Update User',
    apiPath: '/api/v1/users/:id',
    method: 'PATCH',
    module: 'USERS',
  },
  {
    name: 'Delete User',
    apiPath: '/api/v1/users/:id',
    method: 'DELETE',
    module: 'USERS',
  },
  {
    name: 'Upload Single File',
    apiPath: '/api/v1/files/upload',
    method: 'POST',
    module: 'FILES',
  },
  {
    name: 'Create a Job',
    apiPath: '/api/v1/jobs',
    method: 'POST',
    module: 'JOBS',
  },
  {
    name: 'Get a job by id',
    apiPath: '/api/v1/jobs/:id',
    method: 'GET',
    module: 'JOBS',
  },
  {
    name: 'Update a Job',
    apiPath: '/api/v1/jobs/:id',
    method: 'PATCH',
    module: 'JOBS',
  },
  {
    name: 'Get Job with paginate',
    apiPath: '/api/v1/jobs',
    method: 'GET',
    module: 'JOBS',
  },
  {
    name: 'Delete a Job',
    apiPath: '/api/v1/jobs/:id',
    method: 'DELETE',
    module: 'JOBS',
  },
  {
    name: 'Create a Resume',
    apiPath: '/api/v1/resumes',
    method: 'POST',
    module: 'RESUMES',
  },
  {
    name: 'Fetch resume with paginate',
    apiPath: '/api/v1/resumes',
    method: 'GET',
    module: 'RESUMES',
  },
  {
    name: 'Get resume by id',
    apiPath: '/api/v1/resumes/:id',
    method: 'GET',
    module: 'RESUMES',
  },
  {
    name: 'Delete a resume',
    apiPath: '/api/v1/resumes/:id',
    method: 'DELETE',
    module: 'RESUMES',
  },
  {
    name: 'Update resume status',
    apiPath: '/api/v1/resumes/:id',
    method: 'PATCH',
    module: 'RESUMES',
  },
  {
    name: 'Fetch resumes by user',
    apiPath: '/api/v1/resumes/by-user',
    method: 'POST',
    module: 'RESUMES',
  },
  {
    name: 'Create a permission',
    apiPath: '/api/v1/permissions',
    method: 'POST',
    module: 'PERMISSIONS',
  },
  {
    name: 'Fetch Permission with paginate',
    apiPath: '/api/v1/permissions',
    method: 'GET',
    module: 'PERMISSIONS',
  },
  {
    name: 'Fetch permission by id',
    apiPath: '/api/v1/permissions/:id',
    method: 'GET',
    module: 'PERMISSIONS',
  },
  {
    name: 'Update a permission',
    apiPath: '/api/v1/permissions/:id',
    method: 'PATCH',
    module: 'PERMISSIONS',
  },
  {
    name: 'Delete a permission',
    apiPath: '/api/v1/permissions/:id',
    method: 'DELETE',
    module: 'PERMISSIONS',
  },
  {
    name: 'Create Role',
    apiPath: '/api/v1/roles',
    method: 'POST',
    module: 'ROLES',
  },
  {
    name: 'Fetch roles with paginate',
    apiPath: '/api/v1/roles',
    method: 'GET',
    module: 'ROLES',
  },
  {
    name: 'Fetch role by id',
    apiPath: '/api/v1/roles/:id',
    method: 'GET',
    module: 'ROLES',
  },
  {
    name: 'Update Role',
    apiPath: '/api/v1/roles/:id',
    method: 'PATCH',
    module: 'ROLES',
  },
  {
    name: 'Delete a Role',
    apiPath: '/api/v1/roles/:id',
    method: 'DELETE',
    module: 'ROLES',
  },
];
